# Generated by Django 4.2.7 on 2023-11-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.TextField(default='texttexttexttexttext'),
            preserve_default=False,
        ),
    ]
